// <auto-generated />
using System;
using AT.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AT.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250621212357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("AT.Model.CreateCidade", b =>
                {
                    b.Property<string>("CidadeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatePacotesTuriscoPacoteTuriscoID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumHabitantes")
                        .HasColumnType("INTEGER");

                    b.HasKey("CidadeID");

                    b.HasIndex("CreatePacotesTuriscoPacoteTuriscoID");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("AT.Model.CreateCliente", b =>
                {
                    b.Property<string>("ClienteID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("AT.Model.CreatePacotesTurisco", b =>
                {
                    b.Property<string>("PacoteTuriscoID")
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacidadeMax")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDaViagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDoPacote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisDestinoID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("PacoteTuriscoID");

                    b.HasIndex("PaisDestinoID");

                    b.ToTable("PacotesTuriscos");
                });

            modelBuilder.Entity("AT.Model.CreatePaisDestino", b =>
                {
                    b.Property<string>("PaisDestinoID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaisDestinoID");

                    b.ToTable("PaisesDestino");
                });

            modelBuilder.Entity("AT.Model.CreateReservas", b =>
                {
                    b.Property<string>("ReservaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<string>("PacoteTuriscoID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PacotesTuriscoPacoteTuriscoID")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservaID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("PacotesTuriscoPacoteTuriscoID");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("AT.Model.CreateCidade", b =>
                {
                    b.HasOne("AT.Model.CreatePacotesTurisco", null)
                        .WithMany("Cidades")
                        .HasForeignKey("CreatePacotesTuriscoPacoteTuriscoID");
                });

            modelBuilder.Entity("AT.Model.CreatePacotesTurisco", b =>
                {
                    b.HasOne("AT.Model.CreatePaisDestino", "PaisDestino")
                        .WithMany()
                        .HasForeignKey("PaisDestinoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaisDestino");
                });

            modelBuilder.Entity("AT.Model.CreateReservas", b =>
                {
                    b.HasOne("AT.Model.CreateCliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AT.Model.CreatePacotesTurisco", "PacotesTurisco")
                        .WithMany()
                        .HasForeignKey("PacotesTuriscoPacoteTuriscoID");

                    b.Navigation("Cliente");

                    b.Navigation("PacotesTurisco");
                });

            modelBuilder.Entity("AT.Model.CreatePacotesTurisco", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
